import type { UpdateIcon } from "@/enums/UpdateIcon";

// "add" | "correction" | "update" | "delete"
export type UpdateInfo = {
  id: number;
  update: UpdateIcon; // 👈 ici tu réutilises ton type
  date: string;
  version: string;
  fr: string;
  en: string;
  classname: string;
};
export const UpdateInfoList: UpdateInfo[] = [
  {
    id: 1,
    update: "update",
    date: "2025-10-01",
    version: "v0.2.0",
    fr: "Choix de contrat pour les candidatures",
    en: "Contract selection for applications",
    classname: "mt-5",
  },
  {
    id: 2,
    update: "add",
    date: "2025-10-02",
    version: "v0.3.0",
    fr: "Un tableau pour vos archives",
    en: "A chart for your archives",
    classname: "",
  },
  {
    id: 3,
    update: "add",
    date: "2025-10-03",
    version: "v0.3.0",
    fr: "Vos candidature par contrat",
    en: "Your application by contract",
    classname: "mt-5",
  },
    {
    id: 4,
    update: "add",
    date: "2025-10-06",
    version: "v0.4.0",
    fr: "Archiver et restorer une candidature",
    en: "Archive and restore an application",
    classname: "",
  },
      {
    id: 5,
    update: "add",
    date: "2025-10-06",
    version: "v0.4.0",
    fr: "Supprimer une archive",
    en: "Delete an archive",
    classname: "",
  },
        {
    id: 6,
    update: "add",
    date: "2025-10-20",
    version: "v0.4.0",
    fr: "Bouton pour supprimer toutes vos archives",
    en: "Button deletes all your archives",
    classname: "mt-5",
  },
          {
    id: 7,
    update: "add",
    date: "2025-10-28",
    version: "v0.5.0",
    fr: "Mettre votre profil en public et création ou modification de votre pseudo",
    en: "Make your profile public and create or change your username",
    classname: "",
  },
  {
    id: 8,
    update: "correction",
    date: "2025-10-28",
    version: "v0.5.0",
    fr: "Correction d'un problème avec le bouton copier pour le lien de votre profil",
    en: "Fixed an issue with the copy button for your profile link",
    classname: "",
  },
  {
    id: 9,
    update: "correction",
    date: "2026-01-27",
    version: "v0.5.0",
    fr: "Correction du problème lié aux textes trop long qui créaient des décalages sur les cartes de candidature",
    en: "Fixed an issue where overly long text caused misalignment on application cards",
    classname: "",
  },
  {
    id: 10,
    update: "correction",
    date: "2026-02-09",
    version: "v0.5.0",
    fr: "Correction d'un problème d'affichage de la traduction",
    en: "Fixed an issue with translation display",
    classname: "",
  },
  {
    id: 11,
    update: "correction",
    date: "2026-02-09",
    version: "v0.5.0",
    fr: "Correction d'un problème visuel sur mobile pour le lien du profil public dans les paramètres",
    en: "Fixed a visual issue on mobile for the public profile link in Settings",
    classname: "",
  },
  {
    id: 12,
    update: "update",
    date: "2026-02-09",
    version: "v0.5.0",
    fr: "Traduction de la carte profil dans les paramètres",
    en: "Translation of the profile card in the settings",
    classname: "mt-5",
  },
  {
    id: 13,
    update: "add",
    date: "2026-04-10",
    version: "v0.6.0",
    fr: "Vous pouvez maintenant ajouter une candidature qui vous intéresse sans encore y candidater. Elle apparaîtra dans votre liste d'intérêt",
    en: "You can now save a job listing that interests you without applying for it just yet. It will appear in your interest list",
    classname: "",
  },
  {
    id: 14,
    update: "correction",
    date: "2026-04-10",
    version: "v0.6.0",
    fr: "Correction d'un problème visuel dans le formulaire d'ajout de candidature sur mobile",
    en: "Fixed a visual issue with the application submission form on mobile devices",
    classname: "",
  },
  {
    id: 15,
    update: "correction",
    date: "2026-04-24",
    version: "v0.6.1",
    fr: "Correction d'un problème de chargement des candidatures après création ou modification",
    en: "Fixed an issue with loading applications after creation or modification",
    classname: "",
  },
  {
    id: 16,
    update: "update",
    date: "2026-05-08",
    version: "v0.6.2",
    fr: "Mise à jour de l'icône de l'application qui se vois maintenant sur fond blanc",
    en: "The app icon has been updated and is now displayed on a white background",
    classname: "",
  },
  {
    id: 17,
    update: "correction",
    date: "2026-06-01",
    version: "v0.6.3",
    fr: "Correction d'un problème de création du profil lors de l'inscription",
    en: "Fixed an issue with profile creation during registration",
    classname: "",
  },
  {
    id: 18,
    update: "update",
    date: "2026-06-01",
    version: "v0.6.3",
    fr: "Mise à jour de l'affichage du lien dans les cartes candidature pour éviter tout problème avec l'icône de lien",
    en: "Updated the link display in application cards to prevent any issues with the link icon",
    classname: "",
  },
  {
    id: 19,
    update: "correction",
    date: "2026-06-04",
    version: "v0.6.4",
    fr: "Correction de l'ordre d'affichage des candidatures et des offres intéressantes",
    en: "Adjustment of the display order for job applications and interest jobs",
    classname: "",
  },
  {
    id: 20,
    update: "add",
    date: "2026-06-04",
    version: "v0.6.4",
    fr: "Affichage du contrat dans les offres intéressantes",
    en: "Displaying the contract in interesting jobs",
    classname: "mt-5",
  },
  // TODO
  {
    id: 21,
    update: "update",
    date: "2026-07-08",
    version: "v0.7.0",
    fr: "Mise a jour visuel du profil",
    en: "Visual Update to the Profile",
    classname: "",
  },
  {
    id: 22,
    update: "add",
    date: "2026-07-08",
    version: "v0.7.0",
    fr: "Mettre en favoris et accéder à vos favoris depuis votre profil",
    en: "Bookmark and access your bookmarks from your profile",
    classname: "",
  },
  {
    id: 23,
    update: "add",
    date: "2026-07-09",
    version: "v0.7.1",
    fr: "Ajouter des notes depuis votre profil",
    en: "Add notes from your profile",
    classname: "",
  },
  {
    id: 24,
    update: "correction",
    date: "2026-07-09",
    version: "v0.7.1",
    fr: "Correction d'un problème lié à la longueur du titre d'une candidature créant un décalage visuel sur les cartes de candidatures",
    en: "Fixed an issue related to the length of an application's title that caused a visual misalignment on the application cards",
    classname: "",
  },
  {
    id: 25,
    update: "correction",
    date: "2026-07-09",
    version: "v0.7.1",
    fr: "Correction d'une erreur d'affichage quand lors de la modification d'une candidature",
    en: "Fixed a display error that occurred when editing an application",
    classname: "",
  },
];

// Waiting page add
